app:
    resource: "@AppBundle/Controller/"
    type:     annotation

search:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"